apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: odoo-stack
spec:
  # Headless service for StatefulSet stable DNS
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
